import type { Metadata } from "next";
import { Geist, Geist_Mono ,Jost } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import NavbarMenu from "@/components/Navbar";
import Footer from "@/components/Footer";
// import "bootstrap/dist/js/bootstrap.bundle.min.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        style={{ background: "#F5F5F5" }}
        className={`${geistSans.variable} ${geistMono.variable} p-3`}
      >
        <NavbarMenu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
